name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Deploy file
          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          with:
              ftp-server: ${{ secrets. FTP_SERVER }}
              ftp-username: ${{ secrets. FTP_USERNAME}} 
              ftp-password: ${{ secrets. FTP_PASSWORD }}
            
